apiVersion: v1
kind: Namespace
metadata:
  name: agentgateway-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway-crds
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/kgateway-dev/charts/agentgateway-crds
  ref:
    tag: "v2.2.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway-crds
  namespace: agentgateway-system
spec:
  interval: 1h
  releaseName: agentgateway-crds
  chartRef:
    kind: OCIRepository
    name: agentgateway-crds
    namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
