apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/den-vasyliev/gateway-api-crds
  ref:
    tag: "1.4.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gateway-api-crds
  install:
    crds: CreateReplace
