apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kagent-crds
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/kagent-dev/kagent/helm/kagent-crds
  ref:
    semver: ">=0.0.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
  namespace: kagent
spec:
  interval: 1h
  releaseName: kagent-crds
  chartRef:
    kind: OCIRepository
    name: kagent-crds
    namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
