apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agentgateway
  namespace: flux-system
spec:
  interval: 5m
  path: ./infra/manifests/agentgateway
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: infra
