apiVersion: v1
kind: Namespace
metadata:
  name: phoenix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: phoenix
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/arizephoenix/phoenix-helm
  ref:
    tag: "5.0.18"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phoenix
  namespace: phoenix
spec:
  interval: 1h
  releaseName: phoenix
  chartRef:
    kind: OCIRepository
    name: phoenix
    namespace: flux-system

  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    ingress:
      enabled: false

    postgresql:
      enabled: true

    persistence:
      enabled: false

    auth:
      enableAuth: true
      defaultAdminPassword: "Phoenix2026!"

    logging:
      level: info
      dbLevel: warning
